#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libtraceevent
Version  : 1.3.0
Release  : 1
URL      : https://git.kernel.org/pub/scm/libs/libtrace/libtraceevent.git/snapshot/libtraceevent-1.3.0.tar.gz
Source0  : https://git.kernel.org/pub/scm/libs/libtrace/libtraceevent.git/snapshot/libtraceevent-1.3.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.0

%description
The official repository is here:
https://git.kernel.org/pub/scm/libs/libtrace/libtraceevent.git/

%package dev
Summary: dev components for the libtraceevent package.
Group: Development
Provides: libtraceevent-devel = %{version}-%{release}
Requires: libtraceevent = %{version}-%{release}

%description dev
dev components for the libtraceevent package.


%prep
%setup -q -n libtraceevent-1.3.0
cd %{_builddir}/libtraceevent-1.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1621362677
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1621362677
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/lib64/pkgconfig/libtraceevent.pc
