#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v3
# autospec commit: c1050fe
#
Name     : libtraceevent
Version  : 1.8.0
Release  : 22
URL      : https://git.kernel.org/pub/scm/libs/libtrace/libtraceevent.git/snapshot/libtraceevent-1.8.0.tar.gz
Source0  : https://git.kernel.org/pub/scm/libs/libtrace/libtraceevent.git/snapshot/libtraceevent-1.8.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.0
Requires: libtraceevent-lib = %{version}-%{release}
BuildRequires : asciidoc
BuildRequires : buildreq-meson
BuildRequires : pkgconfig(cunit)
BuildRequires : xmlto
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
The official repository is here:
https://git.kernel.org/pub/scm/libs/libtrace/libtraceevent.git/

%package dev
Summary: dev components for the libtraceevent package.
Group: Development
Requires: libtraceevent-lib = %{version}-%{release}
Provides: libtraceevent-devel = %{version}-%{release}
Requires: libtraceevent = %{version}-%{release}

%description dev
dev components for the libtraceevent package.


%package lib
Summary: lib components for the libtraceevent package.
Group: Libraries

%description lib
lib components for the libtraceevent package.


%package staticdev
Summary: staticdev components for the libtraceevent package.
Group: Default
Requires: libtraceevent-dev = %{version}-%{release}

%description staticdev
staticdev components for the libtraceevent package.


%prep
%setup -q -n libtraceevent-1.8.0
cd %{_builddir}/libtraceevent-1.8.0
pushd ..
cp -a libtraceevent-1.8.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1703606630
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -O3" CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
DESTDIR=%{buildroot} ninja -C builddir install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/libtraceevent/plugins/libtraceevent-dynamic-list
/usr/lib64/libtraceevent/plugins/plugin_cfg80211.a
/usr/lib64/libtraceevent/plugins/plugin_function.a
/usr/lib64/libtraceevent/plugins/plugin_futex.a
/usr/lib64/libtraceevent/plugins/plugin_hrtimer.a
/usr/lib64/libtraceevent/plugins/plugin_jbd2.a
/usr/lib64/libtraceevent/plugins/plugin_kmem.a
/usr/lib64/libtraceevent/plugins/plugin_kvm.a
/usr/lib64/libtraceevent/plugins/plugin_mac80211.a
/usr/lib64/libtraceevent/plugins/plugin_sched_switch.a
/usr/lib64/libtraceevent/plugins/plugin_scsi.a
/usr/lib64/libtraceevent/plugins/plugin_tlb.a
/usr/lib64/libtraceevent/plugins/plugin_xen.a

%files dev
%defattr(-,root,root,-)
/usr/include/traceevent/event-parse.h
/usr/include/traceevent/event-utils.h
/usr/include/traceevent/kbuffer.h
/usr/include/traceevent/trace-seq.h
/usr/lib64/libtraceevent.so
/usr/lib64/pkgconfig/libtraceevent.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libtraceevent.so.1.8.0
/V3/usr/lib64/libtraceevent/plugins/plugin_cfg80211.so.1.8.0
/V3/usr/lib64/libtraceevent/plugins/plugin_function.so.1.8.0
/V3/usr/lib64/libtraceevent/plugins/plugin_futex.so.1.8.0
/V3/usr/lib64/libtraceevent/plugins/plugin_hrtimer.so.1.8.0
/V3/usr/lib64/libtraceevent/plugins/plugin_jbd2.so.1.8.0
/V3/usr/lib64/libtraceevent/plugins/plugin_kmem.so.1.8.0
/V3/usr/lib64/libtraceevent/plugins/plugin_kvm.so.1.8.0
/V3/usr/lib64/libtraceevent/plugins/plugin_mac80211.so.1.8.0
/V3/usr/lib64/libtraceevent/plugins/plugin_sched_switch.so.1.8.0
/V3/usr/lib64/libtraceevent/plugins/plugin_scsi.so.1.8.0
/V3/usr/lib64/libtraceevent/plugins/plugin_tlb.so.1.8.0
/V3/usr/lib64/libtraceevent/plugins/plugin_xen.so.1.8.0
/usr/lib64/libtraceevent.so.1
/usr/lib64/libtraceevent.so.1.8.0
/usr/lib64/libtraceevent/plugins/plugin_cfg80211.so
/usr/lib64/libtraceevent/plugins/plugin_cfg80211.so.1
/usr/lib64/libtraceevent/plugins/plugin_cfg80211.so.1.8.0
/usr/lib64/libtraceevent/plugins/plugin_function.so
/usr/lib64/libtraceevent/plugins/plugin_function.so.1
/usr/lib64/libtraceevent/plugins/plugin_function.so.1.8.0
/usr/lib64/libtraceevent/plugins/plugin_futex.so
/usr/lib64/libtraceevent/plugins/plugin_futex.so.1
/usr/lib64/libtraceevent/plugins/plugin_futex.so.1.8.0
/usr/lib64/libtraceevent/plugins/plugin_hrtimer.so
/usr/lib64/libtraceevent/plugins/plugin_hrtimer.so.1
/usr/lib64/libtraceevent/plugins/plugin_hrtimer.so.1.8.0
/usr/lib64/libtraceevent/plugins/plugin_jbd2.so
/usr/lib64/libtraceevent/plugins/plugin_jbd2.so.1
/usr/lib64/libtraceevent/plugins/plugin_jbd2.so.1.8.0
/usr/lib64/libtraceevent/plugins/plugin_kmem.so
/usr/lib64/libtraceevent/plugins/plugin_kmem.so.1
/usr/lib64/libtraceevent/plugins/plugin_kmem.so.1.8.0
/usr/lib64/libtraceevent/plugins/plugin_kvm.so
/usr/lib64/libtraceevent/plugins/plugin_kvm.so.1
/usr/lib64/libtraceevent/plugins/plugin_kvm.so.1.8.0
/usr/lib64/libtraceevent/plugins/plugin_mac80211.so
/usr/lib64/libtraceevent/plugins/plugin_mac80211.so.1
/usr/lib64/libtraceevent/plugins/plugin_mac80211.so.1.8.0
/usr/lib64/libtraceevent/plugins/plugin_sched_switch.so
/usr/lib64/libtraceevent/plugins/plugin_sched_switch.so.1
/usr/lib64/libtraceevent/plugins/plugin_sched_switch.so.1.8.0
/usr/lib64/libtraceevent/plugins/plugin_scsi.so
/usr/lib64/libtraceevent/plugins/plugin_scsi.so.1
/usr/lib64/libtraceevent/plugins/plugin_scsi.so.1.8.0
/usr/lib64/libtraceevent/plugins/plugin_tlb.so
/usr/lib64/libtraceevent/plugins/plugin_tlb.so.1
/usr/lib64/libtraceevent/plugins/plugin_tlb.so.1.8.0
/usr/lib64/libtraceevent/plugins/plugin_xen.so
/usr/lib64/libtraceevent/plugins/plugin_xen.so.1
/usr/lib64/libtraceevent/plugins/plugin_xen.so.1.8.0

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libtraceevent.a
